Primer Push
Milovar/psl-workshop-api-testing-js pull request #1
Opened 2017-09-22 21:27 UTC by Milovar

2017-09-22 21:36 UTC, germandavid85 requested changes

2017-09-22 21:36 UTC, germandavid85 commented on test/HelloWord.test.js
> +describe( '#indexOf()' , () => {
corregir indentaciones

2017-09-22 21:36 UTC, germandavid85 commented on test/HelloWord.test.js
> +});
adicionar linea en blanco

2017-09-22 21:55 UTC, germandavid85 approved these changes

2017-09-24 16:32 UTC, aperdomob approved these changes

2017-09-25 13:56 UTC, jhenaoz approved these changes

2017-09-25 19:52 UTC, merged