Deuda Tecnica - Carga archivo travis
Milovar/psl-workshop-api-testing-js pull request #3
Opened 2017-09-27 20:11 UTC by Milovar

2017-09-27 21:35 UTC, germandavid85 requested changes

2017-09-27 21:35 UTC, germandavid85 commented on .travis.yml
> +
adiciona linea en blanco al final del archivo

2017-09-27 22:07 UTC, Milovar commented on .travis.yml
> +
Hola German, yo veo el espacio en mi local
![espacio](https://user-images.githubusercontent.com/32206813/30940340-59abebb8-a3a6-11e7-993f-e033ef844b17.PNG)

2017-09-27 22:28 UTC, aperdomob commented on .travis.yml
> +
Allí se ve que hay un espacio :)

2017-09-29 14:30 UTC, jhenaoz approved these changes

2017-09-29 14:33 UTC, jhenaoz requested changes
La integracion continua en travis esta fallando, dice que falta una libreria que no veo en el package.json super-agent.

2017-09-29 15:01 UTC, jhenaoz approved these changes

2017-09-29 15:19 UTC, aperdomob requested changes
continuas con el error del espacio

2017-10-02 14:20 UTC, merged